<a href="https://colab.research.google.com/github/somalur/Pytorch-Test/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

**List**

In [3]:
my_list = [[1,2,3,4,5],[6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

**Numpy Array**

In [4]:
np1 = np.random.rand(3,4)
np1

array([[0.11227673, 0.39509173, 0.87499645, 0.06279453],
       [0.07266061, 0.81486384, 0.95797477, 0.64225218],
       [0.76233319, 0.90470978, 0.23556712, 0.11546258]])

Tensor

In [5]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[-0.1584,  0.0023, -0.3236,  0.4373],
        [ 0.7619,  0.1695,  0.5771, -0.6750],
        [-0.7558, -0.1732,  1.8044, -0.2414]])

In [6]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

Create Tensor from Numpy Array



In [7]:
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.1123, 0.3951, 0.8750, 0.0628],
        [0.0727, 0.8149, 0.9580, 0.6423],
        [0.7623, 0.9047, 0.2356, 0.1155]], dtype=torch.float64)